### ISSUE TITLE
组件的原show,hide方法参数带不过去

### ISSUE THREAD

**Issue by kallsave** [cube-ui/vue-create-api#10]
如果组件有show,hide方法,并且有参数,createApi创建后参数带不过去了，show,hide方法的参数可以控制是否删除缓存，还有第三方ui库的show方法也是有参数的情况，希望能兼容下...  谢谢大佬~

**Comment by ustbhuangyi** [comment]
pr welcome

**Comment by ustbhuangyi** [comment]
v0.2.2
