### ISSUE TITLE
如何在使用vue-create-api 弹出框中使用vuex 和vue-router

### ISSUE THREAD

**Issue by quanzhiyuan** [cube-ui/vue-create-api#13]
如何在使用vue-create-api 弹出框中使用vuex 和vue-router

**Comment by dolymood** [comment]
在调用组件上下文内 传入 就可以了吧

**Comment by tedtse** [comment]
比如 在 index.vue 文件里引入 name 为 "Dialog" 的组件
Dialog.$create 的上下文不是 index.vue 的 this
this.$createDialog 的上下文是 index.vue 的 this
