### ISSUE TITLE
使用该插件会导致打包后的代码体积增加

### ISSUE THREAD

**Issue by rossroma** [cube-ui/vue-create-api#25]
因为项目中使用了cube-ui，因此可能被动的使用了该插件。然后观察打包后的代码，发现多处该插件的实例。
![image](https://user-images.githubusercontent.com/6183683/108713155-cb174500-7552-11eb-9910-b9c3752b7820.png)
即便代码压缩混淆后，每个实例仍有50kb左右的大小，请问这是正常现象吗？有无优化方法？

**Comment by dolymood** [comment]
看起来是自身项目构建打包引起的问题
