### ISSUE TITLE
中文文档，vue-create-api 引入错误

### ISSUE THREAD

**Issue by b1g3rr0r** [cube-ui/vue-create-api#4]
[中文文档 - 使用](https://github.com/cube-ui/vue-create-api/blob/master/README_zh-CN.md#%E4%BD%BF%E7%94%A8) 中

`import CreateAPI from 'create-api'`

应改成

`import CreateAPI from 'vue-create-api'`

**Comment by dolymood** [comment]
多谢反馈 已修
