### ISSUE TITLE
监听属性必须是实例根属性的问题

### ISSUE THREAD

**Issue by xiaohaiH** [cube-ui/vue-create-api#5]
https://github.com/cube-ui/vue-create-api/blob/ca632ee08290b92151b7a7e802b77135dfd8a6bc/src/creator.js#L71
propKey 如果是 'a.b' 就监听不到了,  这个地方可以调整下吗? 对句号进行切割在进行判断

**Comment by dolymood** [comment]
这个情况太复杂了，不只是 'a.b' 还有更复杂的case，这种建议直接使用 computed 特性实现即可。
