### ISSUE TITLE
组件内this.remove报错问题

### ISSUE THREAD

**Issue by dengwb1991** [cube-ui/vue-create-api#9]
**错误日志**：[Vue warn]: Error in event handler for "hook:beforeDestroy": "TypeError: Cannot read property 'removeChild' of null"

**原因**：在组件内部调用this.remove方法后，creator.js约167行 `ownerInstance.$on(eventBeforeDestroy, beforeDestroy) 并未执行$off` 导致实例已经销毁，却还要删除dom引发。

**暂时解决**：在Vue.createAPI新增一个字段(isDestroy) 判断创建时是否需要绑定($on....)

相关代码链接：
[组件](https://github.com/dengwb1991/owl-ui/blob/master/packages/toast/src/main.vue)
[create-api](https://github.com/dengwb1991/owl-ui/tree/master/src/utils/create-api)
[示例](https://github.com/dengwb1991/owl-ui/tree/master/examples/view/toast)

**Comment by dolymood** [comment]
组件本身不应该有移除自设的逻辑，组件的销毁是应该由外部来控制，而非自身，自身实际也是控制不了
